name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Run Tests
        run: npm test
      - name: Deploy to Github Pages
        run: |
          git config --global user.email ${{ secrets.GH_EMAIL }}
          git config --global user.name ${{ secrets.GH_USERNAME }}
          git remote set-url origin https://${{ secrets.GH_ACTIONS_TOKEN }}@github.com/${{ secrets.GH_USERNAME }}/Cubos-website.git
          npm run deploy
